### ISSUE TITLE
Where is backup?

### ISSUE THREAD

**Issue by lortaie** [uM0d/Moov-Now-swimming-data-export#1]
Hi there, first of all thanks a lot for your effort.
After installing the APK I've tried to find the backup folder on my Android phone by searching or installing even a device for explorer however with no luck. May I have done something strange while installing? I'm not a programmer. Thanks again
Giuseppe

**Comment by uM0d** [comment]
The **MoovBackup** folder is created when the swimming session log is opened.
![Screenshot2](https://user-images.githubusercontent.com/53191596/72631207-9d79c880-395c-11ea-81d1-f6971fe88981.png)

**Comment by uM0d** [comment]
Please check the application's storage permissions.
