### ISSUE TITLE
Does not install on Android.

### ISSUE THREAD

**Issue by frednickler** [uM0d/Moov-Now-swimming-data-export#2]
Hi, @uM0d

Awesome work there!!
Downloaded the APK and tried to install on my S8, tried to install after already installing the original version but, although it said it would only update that version in the end it said "app not installed".

So, do I have to first uninstall the official version?

Many thanks.

**Comment by uM0d** [comment]
Yes, you must uninstall the official version before installing this modified version and you must allow installation from unknown sources.
But you can install this modified version only for swimming backup (.csv and .fit) on another Android device or android emulator for PC and keep the official application on S8.
Another solution might be to install the Dual Space - Multiple Accounts & App Cloner from Google Play on the S8 and install the modified version there and you will have both versions on the S8.

**Comment by frednickler** [comment]
Sweet.

I try it out.
Thanks!!

Any way of getting anymore information export out?
Also is it possible to import data in to maybe replace data that was recorded incorrectly?
Cheers,

**Comment by uM0d** [comment]
You can try to load your .fit file to :
-  http://www.swimmingwatchtools.com/
-  https://www.goldencheetah.org/
-  https://www.swim.com/
