### ISSUE TITLE
Can't get it to work :(

### ISSUE THREAD

**Issue by frednickler** [uM0d/Moov-Now-swimming-data-export#3]
@uM0d 

Thanks for your attention.

  So, these are the steps I took to try and get the app to work.

1)Installed the modified version on another android phone 2 and kept the original version on phone 1. All the swims are shown on phone 2, same data as the original on phone 1.
2)Allowed debugging on phone 2 and connected to pc.
3)Opened a swim session on phone 2 while connected to pc and nothing happened.
4)Installed Vysor to mirror the phone on pc and followed your instructions and still can't see the Moovbackup folder.

None of my phones are rooted, should they be? Phone 1 S8 and phone 2 S5.
Tried on Windows and mac. 

I also noted that you your screenshots from Nox are on android 5, my phone 2 is on android 6.0.1, would that be an issue?

Thank again for your help.

**Comment by uM0d** [comment]
Step 2) 3) is not necessary and may be the problem.
Do not connect your computer while trying to back up.
After you open a swimming session, you will find a new "MoovBackup" folder. In this folder you can find .fit and .csv files of previously opened swimming sessions.

You can also install an SD card on the S5. The backup folder is created into a real or emulated SD card. You can access this folder using any file explorer.

Also check the permissions of the application.
Please let me know if you did.

![Allowed](https://user-images.githubusercontent.com/53191596/79745723-793dd700-8311-11ea-9ad2-c5438ef9805b.png)
![Allow](https://user-images.githubusercontent.com/53191596/79745711-75aa5000-8311-11ea-8eb0-f8967847a16c.png)


![Screenshot2](https://user-images.githubusercontent.com/53191596/79727294-dd05d700-82f4-11ea-81d7-c1e535068085.png)

**Comment by frednickler** [comment]
SWEET!!!!

The whole deal was giving the app storage permission.
I don't remember being asked to give it permission when I installed it.
Maybe you should add this detail in the main instructions page.

Thanks again!!!
